---
- name: add ntp server to /etc/ntp.conf
  lineinfile:
     path: /etc/ntp.conf
     line: "{{ item }}"
  with_items:
     - server 0.rhel.pool.ntp.org iburst
     - server 1.rhel.pool.ntp.org iburst
     - server 2.rhel.pool.ntp.org iburst
     - server 3.rhel.pool.ntp.org iburst

- name: restart ntpd service
  service:
     name: ntpd
     state: restarted

- name: enable ntpd service
  service:
     name: ntpd
     enabled: yes

- name: modify time zone into /etc/sysconfig/clock
  replace:
     path: /etc/sysconfig/clock
     regexp: '^ZONE=.*$'
     replace: ZONE="Europe/Bucharest"
     backup: yes

- name: create symlink from /usr/share/zoneinfo/Europe/Bucharest to /etc/localtime
  file:
     src: /usr/share/zoneinfo/Europe/Bucharest
     path: /etc/localtime
     state: link
