---
- name: unachive kernel_2.6.32-573.12.1.el6x86_64.tar on the remote machine
  copy:
     src: /path/on/ansible/server/kernel_2.6.32-573.12.1.el6x86_64.tar
     dest: /images/kernel_2.6.32-573.12.1.el6x86_64.tar

- name: install kernel using yum
  yum:
    name: "/images/kernel/{{ item }}"
  with_items:
    - dracut-004-388.el6.noarch.rpm
    - dracut-kernel-004-388.el6.noarch.rpm
    - kernel-firmware-2.6.32-573.12.1.el6.noarch.rpm
    - kernel-2.6.32-573.12.1.el6.x86_64.rpm
